# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2274a5a7b74ebb4a518c6290f5fe0b7e46c6a3a85d11802dfa5527d5c53cb1a5ed51f908403553418980a59074e3bc69d44a2841fb7111f07973fa3f78f64df6

test:
  secret_key_base: fa555de1c33a83aa3831f1e053840ce864d883b9e5257f6f89c252e60731590058284b504848516f21d22a3454e3b6c371e2dc4feed0245551feefcdd180e74f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
